[build]
  # Build command for the frontend without static export (removed export for i18n compatibility)
  command = "cd frontend/autoani && npm ci && npm run build"
  # Published directory for Next.js with i18n support
  publish = "frontend/autoani/.next"
  # Base directory
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Environment for Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  # Required for Netlify to properly handle Next.js
  NEXT_PRIVATE_TARGET = "server"

# Use the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects and rewrites for Next.js
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Fallback for all routes - very important for Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

[dev]
  framework = "nextjs"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
