[build]
  # Build command for the frontend without static export (removed export for i18n compatibility)
  command = "cd frontend/autoani && npm ci && npm run build"
  # Published directory for Next.js with i18n support
  publish = "frontend/autoani/.next"
  # Base directory
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Environment for Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  # Add this for Netlify to use Next.js
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# For client-side routing in SPA mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "nextjs"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
