[build]
  # Build command for the frontend
  command = "cd frontend/autoani && npm ci && npm run build"
  # Published directory
  publish = "frontend/autoani/.next"
  # Base directory
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Environment for Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  # Add required environment variables for Next.js plugin
  NEXT_PRIVATE_TARGET = "server" 
  # Specify build output directory for Next.js
  NETLIFY_NEXT_BASE_DIR = "frontend/autoani"

# Netlify rewrites and proxies for Next.js
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_render/:splat"
  status = 200

# Fallback for client-side routing in SPA mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions directory for API endpoints (if needed later)
[functions]
  directory = "netlify/functions"
