# Netlify configuration for Next.js project

[build]
  # The build command for Next.js
  command = "npm run build"
  publish = ".next"

# This plugin automatically configures your Next.js site on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Environment for Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PRIVATE_TARGET = "server"

